### ISSUE TITLE
Add characters for chikari

### ISSUE THREAD

**Issue by Technofidget** [omenad/fonts#64]
Sometimes it is necessary to be able to write the fact that we must play a chi.

In this case, in the written score, we use the letter 'o' or the symbol '>'.

Is it possible to have a symbol to represent this ?

**Comment by rajadain** [comment]
Can you share any screenshots or sketches of the Chikari symbol in context with notes / composition?

**Comment by jain-sanjay** [comment]
Ravi Shankar in his book suggests to use letter c for chikari.
I asked around, some people use * and some others use $
There is no universal symbol for this. I want to suggest the attached which is close to Ravi Shankar but more representative of a Music Notation.
![chickari](https://github.com/user-attachments/assets/dc3c68c5-c5b1-49b1-9820-da2a9f951ec8)

**Comment by Technofidget** [comment]
There was an old font called Dustismo Sargam that allows to write chikari with a little 'C' character in the upper corner.
For example if we play Sa then a Chi we will write this :
![image](https://github.com/user-attachments/assets/33cce1a5-bdcc-44cf-b39d-641c0d050bb1)

**Comment by rajadain** [comment]
Hi folks, sorry for the delay on this. After consulting with various experts, we will not add a Chikari character to the font. This is because of two reasons:

1. There is no standard symbol for this. While a number have been proposed, none are standard to Bhatkhande.
2. There is no chikari symbol in the Misrabani style. Chikari is optional adornment, played at the discretion of the musician, not explicitly required in a composition. A chikari may be played during a khali matra, but is not indicated explicitly.
